"""Run the scenario matrix and write docs/SIM-RESULTS.md.

Usage:  python3 sim/run.py
"""

import os
import statistics
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import model  # noqa: E402
from model import run_journey  # noqa: E402
from routes import ALL_ROUTES, LONG_JOURNEY_MIN_HR  # noqa: E402

STRATEGIES = [90.0, 100.0, 110.0, 120.0, 130.0]
LEGAL = 999.0  # "legal maximum throughout"
BASELINE = 100.0  # fixed reference for the marginal-rate calculation
EXPONENTS = [3, 4, 5]

# Falsification thresholds, fixed in advance per SIM-PRD section 8.1.
THRESHOLD_STRONG_MIN = 5.0
THRESHOLD_WEAK_MIN = 10.0


def hm(hours):
    h = int(hours)
    m = int(round((hours - h) * 60))
    if m == 60:
        h, m = h + 1, 0
    return f"{h}h{m:02d}"


def raw_time_removed_hr(journey, cap_low, cap_high):
    """Driving time removed on speed-elastic segments, ignoring mechanisms."""
    total = 0.0
    for seg in journey.segments:
        v_lo = min(cap_low, seg.legal_limit_kmh, seg.free_flow_kmh)
        v_hi = min(cap_high, seg.legal_limit_kmh, seg.free_flow_kmh)
        total += seg.length_km / v_lo - seg.length_km / v_hi
    return total


def analyse(journey):
    caps = STRATEGIES + [LEGAL]
    runs = {cap: run_journey(journey, cap) for cap in caps}
    long_journey = runs[110.0].total_hr >= LONG_JOURNEY_MIN_HR

    steps = []
    for lo, hi in zip(STRATEGIES, STRATEGIES[1:]):
        actual = (runs[lo].total_hr - runs[hi].total_hr) * 60.0
        raw = raw_time_removed_hr(journey, lo, hi) * 60.0
        risk = {
            e: runs[hi].risk_index(e) / runs[lo].risk_index(e) for e in EXPONENTS
        }
        steps.append(
            {
                "lo": lo,
                "hi": hi,
                "actual_min": actual,
                "raw_min": raw,
                "pass_through": (actual / raw) if raw > 1e-9 else float("nan"),
                "risk": risk,
                "min_per_risk": (
                    actual / (risk[4] - 1.0) if risk[4] > 1.0 + 1e-9 else float("inf")
                ),
                "extra_overtakes": runs[hi].total_overtakes
                - runs[lo].total_overtakes,
            }
        )

    marginal = []
    for cap in STRATEGIES[1:]:
        dt = (runs[BASELINE].total_hr - runs[cap].total_hr) * 60.0
        ratio = runs[cap].risk_index(4) / runs[BASELINE].risk_index(4)
        marginal.append(
            {
                "cap": cap,
                "minutes_vs_base": dt,
                "risk_ratio": ratio,
                "min_per_risk": dt / (ratio - 1.0) if ratio > 1.0 + 1e-9 else float("inf"),
            }
        )

    mechanisms = sorted(
        {s.mechanism for s in journey.segments if s.mechanism != model.NONE}
    )
    return {
        "journey": journey,
        "runs": runs,
        "steps": steps,
        "marginal": marginal,
        "long": long_journey,
        "mechanisms": mechanisms or ["none"],
    }


def step_110_120(a):
    return next(s for s in a["steps"] if s["lo"] == 110.0)


def fmt(x, nd=1):
    if x != x:
        return "n/a"
    if x == float("inf"):
        return "inf"
    return f"{x:.{nd}f}"


def build_report(analyses):
    L = []
    w = L.append

    w("# Marginal Value of Speed — Phase 1 Results")
    w("")
    w("**Generated by:** `sim/run.py` (synthetic routes, no external data)")
    w("**Spec:** `SIM-PRD.md`")
    w("**Thresholds:** fixed in advance — strong < 5 min, weak > 10 min "
      "on the 110→120 step for journeys of 3h+")
    w("")
    w("---")
    w("")

    long_ones = [a for a in analyses if a["long"]]
    mabs = [step_110_120(a)["actual_min"] for a in long_ones]
    median_mab = statistics.median(mabs)

    if median_mab < THRESHOLD_STRONG_MIN:
        verdict, band = "THESIS STRONG", "strong"
    elif median_mab <= THRESHOLD_WEAK_MIN:
        verdict, band = "THESIS CONDITIONAL", "conditional"
    else:
        verdict, band = "THESIS WEAK", "weak"

    w("## Verdict")
    w("")
    w(f"**Time thesis: {verdict}.** Median 110→120 benefit across "
      f"{len(long_ones)} journeys of 3h+ is **{median_mab:.1f} minutes** "
      f"(range {min(mabs):.1f} to {max(mabs):.1f}).")
    w("")

    pts = [
        step_110_120(a)["pass_through"]
        for a in long_ones
        if step_110_120(a)["pass_through"] == step_110_120(a)["pass_through"]
    ]
    median_pt = statistics.median(pts)
    w(f"**Median pass-through ratio: {median_pt:.2f}.** Of the driving time "
      "removed on speed-elastic segments, this is the fraction that reaches "
      "the destination.")
    w("")
    if median_pt > 0.8:
        w("Pass-through above 0.8 triggers the SIM-PRD section 8.1 supporting "
          "criterion: the \"gains evaporate downstream\" framing is not "
          "supportable and must come out of PCS.md on accuracy grounds, "
          "independent of the product decision.")
    w("")

    w("---")
    w("")
    w("## Per-route results")
    w("")
    w("| Route | Mech | 3h+ | Dist | Time @110 | 110→120 | Raw | Pass-thru | SEF |")
    w("| --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    for a in analyses:
        s = step_110_120(a)
        r110 = a["runs"][110.0]
        w(
            f"| {a['journey'].name} | {'/'.join(a['mechanisms'])} | "
            f"{'yes' if a['long'] else 'no'} | {r110.distance_km:.0f} km | "
            f"{hm(r110.total_hr)} | **{fmt(s['actual_min'])} min** | "
            f"{fmt(s['raw_min'])} min | {fmt(s['pass_through'], 2)} | "
            f"{r110.speed_elastic_fraction:.0%} |"
        )
    w("")
    w("*SEF = speed-elastic fraction: share of distance where the 110 cap was "
      "the binding constraint.*")
    w("")

    w("---")
    w("")
    w("## Risk-adjusted trade")
    w("")
    w("Minutes bought per 100% increase in fatal-crash risk, measured against "
      f"a fixed {BASELINE:.0f} km/h baseline at exponent 4. Theory predicts "
      "this falls with roughly the fifth power of speed.")
    w("")
    w("| Route | @110 | @120 | @130 |")
    w("| --- | --- | --- | --- |")
    for a in analyses:
        cells = []
        for cap in (110.0, 120.0, 130.0):
            m = next((x for x in a["marginal"] if x["cap"] == cap), None)
            cells.append(fmt(m["min_per_risk"]) if m else "n/a")
        w(f"| {a['journey'].name} | " + " | ".join(cells) + " |")
    w("")

    w("### Exponent sensitivity")
    w("")
    w("Risk multiplier for the 110→120 step under each candidate exponent. "
      "Conclusions must not depend on a single parameter choice.")
    w("")
    w("| Route | exp 3 | exp 4 | exp 5 |")
    w("| --- | --- | --- | --- |")
    for a in analyses:
        s = step_110_120(a)
        w(
            f"| {a['journey'].name} | ×{s['risk'][3]:.3f} | "
            f"×{s['risk'][4]:.3f} | ×{s['risk'][5]:.3f} |"
        )
    w("")

    w("---")
    w("")
    w("## Mechanism behaviour")
    w("")
    w("Pass-through by mechanism, on the 110→120 step. This is the Claim A "
      "test: below 1.0 means upstream gains are absorbed, at 1.0 they pass "
      "through untouched, above 1.0 they are amplified.")
    w("")
    w("| Route | Mechanism | Pass-through | Reading |")
    w("| --- | --- | --- | --- |")
    for a in analyses:
        s = step_110_120(a)
        pt = s["pass_through"]
        if pt != pt:
            reading = "no elastic distance"
        elif pt > 1.05:
            reading = "amplifies gains"
        elif pt > 0.95:
            reading = "passes gains through"
        elif pt > 0.5:
            reading = "partially absorbs"
        else:
            reading = "absorbs most gains"
        w(
            f"| {a['journey'].name} | {'/'.join(a['mechanisms'])} | "
            f"{fmt(pt, 2)} | {reading} |"
        )
    w("")

    w("---")
    w("")
    w("## Attainability (M5)")
    w("")
    a_i = next(a for a in analyses if a["journey"].name.startswith("I:"))
    w("| Cap | Realized mean | Attainment of increment | Time | Overtakes |")
    w("| --- | --- | --- | --- | --- |")
    base_run = a_i["runs"][90.0]
    for cap in STRATEGIES:
        r = a_i["runs"][cap]
        seg = r.segments[0]
        stream = a_i["journey"].segments[0].params["stream_mean_kmh"]
        intended = min(cap, 130.0)
        att = (
            (seg.realized_kmh - stream) / (intended - stream)
            if intended > stream
            else 1.0
        )
        w(
            f"| {cap:.0f} | {seg.realized_kmh:.1f} km/h | {att:.0%} | "
            f"{hm(r.total_hr)} | {seg.overtakes:.0f} |"
        )
    w("")
    w(f"*Stream mean 90 km/h, density "
      f"{a_i['journey'].segments[0].params['density_veh_per_km']:.0f} veh/km, "
      "single carriageway, 200 km.*")
    w("")

    w("### M5 calibration sensitivity")
    w("")
    w("The overtaking-resistance parameter is an engineering estimate, not an "
      "empirical fit. Realized speed at a 130 cap under a range of values:")
    w("")
    w("| Resistance | Realized mean | Time saved vs 110 cap | Overtakes |")
    w("| --- | --- | --- | --- |")
    original = model.OVERTAKE_RESISTANCE["single"]
    for res in (0.6, 0.9, 1.2, 1.8, 2.4):
        model.OVERTAKE_RESISTANCE["single"] = res
        r130 = run_journey(a_i["journey"], 130.0)
        r110 = run_journey(a_i["journey"], 110.0)
        saved = (r110.total_hr - r130.total_hr) * 60.0
        w(
            f"| {res:.1f} | {r130.segments[0].realized_kmh:.1f} km/h | "
            f"{saved:.1f} min | {r130.segments[0].overtakes:.0f} |"
        )
    model.OVERTAKE_RESISTANCE["single"] = original
    w("")

    w("---")
    w("")
    w("## Full strategy matrix")
    w("")
    w("Total journey time by cruising cap.")
    w("")
    header = " | ".join(f"{c:.0f}" for c in STRATEGIES)
    w(f"| Route | {header} | legal |")
    w("| --- | " + " | ".join(["---"] * (len(STRATEGIES) + 1)) + " |")
    for a in analyses:
        cells = [hm(a["runs"][c].total_hr) for c in STRATEGIES]
        cells.append(hm(a["runs"][LEGAL].total_hr))
        w(f"| {a['journey'].name} | " + " | ".join(cells) + " |")
    w("")

    return "\n".join(L) + "\n", band, median_mab, median_pt


def main():
    analyses = [analyse(j) for j in ALL_ROUTES]
    report, band, median_mab, median_pt = build_report(analyses)

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, os.pardir, "docs", "SIM-RESULTS.md")
    with open(os.path.abspath(out), "w") as f:
        f.write(report)

    print(f"median 110->120 benefit (3h+ journeys): {median_mab:.1f} min")
    print(f"median pass-through:                    {median_pt:.2f}")
    print(f"band:                                   {band}")
    print(f"written: {os.path.abspath(out)}")


if __name__ == "__main__":
    main()
